# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUbGFGblUbDHP_sYnO-INmri7RR4u2jI
"""

import streamlit as st
import requests
import urllib.parse
import time

# 웹 앱 페이지 설정
st.set_page_config(page_title="이치방쿠지 통털이 계산기", page_icon="🐉")

# 스타일링 (가독성 높이기)
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #FF4B4B; color: white; }
    </style>
    """, unsafe_allow_html=True)

st.title("🐉 이치방쿠지 통털이 계산기")
st.caption("번개장터 최신 실거래 '최저가' 기준으로 분석합니다.")

# --- 시세 추출 함수 ---
def get_bunjang_safe_price(keyword):
    search_term = keyword.lower()
    encoded_keyword = urllib.parse.quote(search_term)
    recent_prices = []
    bad_keywords = ["일괄", "세트", "set", "전부", "다해서", "포함", "처분", "정리", "예약", "결제창"]

    try:
        bj_url = f"https://api.bunjang.co.kr/api/1/find_v2.json?q={encoded_keyword}&n=15&order=date&status=3"
        bj_res = requests.get(bj_url, timeout=5).json()

        for item in bj_res.get('list', []):
            if len(recent_prices) >= 3: break
            title = item.get('name', '').lower()
            price = int(item.get('price', 0))
            if any(bad in title for bad in bad_keywords): continue
            if 10000 < price < 2000000:
                recent_prices.append(price)
    except:
        pass
    return min(recent_prices) if recent_prices else 0

# --- UI 입력 섹션 ---
with st.container():
    col1, col2 = st.columns(2)
    with col1:
        series_name = st.text_input("시리즈명", placeholder="예: 헌터헌터")
    with col2:
        unit_price = st.text_input("회당 가격", placeholder="예: 12000")

    remains = st.text_input("남은 장수", placeholder="예: 15")

# 상위상 설정
st.divider()
st.subheader("💎 남은 상위상 설정")
has_prizes = st.radio("상위상이 남아있나요?", ["없음", "있음"], horizontal=True)

prize_data = []
if has_prizes == "있음":
    cols = st.columns(2)
    for i in range(4):
        with cols[i % 2]:
            p_type = st.selectbox(f"상위상 {i+1} 종류", ["-", "A", "B", "C", "D", "E", "F"], key=f"type_{i}")
            p_count = st.number_input(f"상위상 {i+1} 개수", min_value=1, value=1, key=f"count_{i}")
            if p_type != "-":
                prize_data.append((p_type, p_count))

# --- 계산 및 결과 출력 ---
if st.button("💰 수익성 분석 시작"):
    if not series_name or not unit_price or not remains:
        st.error("모든 필수 정보를 입력해주세요!")
    else:
        with st.spinner('최신 시세를 분석 중입니다...'):
            total_investment = int(unit_price) * int(remains)
            total_market_value = 0

            # 라스트원 검색
            lo_price = get_bunjang_safe_price(f"{series_name} 라스트원")
            total_market_value += lo_price

            st.info(f"📦 라스트원 안전 시세: {lo_price:,}원")

            # 상위상 검색
            for pt, pc in prize_data:
                p_val = get_bunjang_safe_price(f"{series_name} {pt}상")
                if p_val == 0: p_val = get_bunjang_safe_price(f"{series_name} {pt}")
                total_market_value += (p_val * pc)
                st.write(f"💎 {pt}상(x{pc}) 안전 시세: {p_val:,}원")
                time.sleep(0.3)

            profit = total_market_value - total_investment

            st.divider()
            st.metric("예상 수익", f"{profit:,}원", delta=f"{profit:,}원")

            if profit > 0:
                st.balloons()
                st.success("✅ 결론: 통털이 추천! 최저가 기준임에도 이득입니다.")
            else:
                st.warning("❌ 결론: 비추천. 손해가 예상됩니다.")